# Generated by Django 4.0.1 on 2022-02-16 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_emailreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreport',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
