# Generated by Django 4.0.1 on 2022-02-17 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_emailreport_time_zone_alter_emailreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreport',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
