# Generated by Django 4.0.1 on 2022-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_emailreport_time_alter_emailreport_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreport',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
