# Generated by Django 4.0.1 on 2022-02-16 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_emailreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 13, 57, 13, 803531, tzinfo=utc)),
        ),
    ]
