# Generated by Django 4.0.1 on 2022-02-16 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_emailreport_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreport',
            name='time_zone',
        ),
        migrations.AlterField(
            model_name='emailreport',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
